types:
  # Features: A new feature.
  - feat
  # Bug Fixes: A bug fix.
  - fix
  # Documentation: Documentation only changes.
  - docs
  # Styles: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
  - style
  # Code Refactoring: A code change that neither fixes a bug nor adds a feature.
  - refactor
  # Performance Improvements: A code change that improves performance.
  - perf
  # Tests: Adding missing tests or correcting existing tests.
  - test
  # Builds: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm).
  - build
  # Continuous Integrations: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs).
  - ci
  # Chores: Other changes that don't modify src or test files.
  - chore
  # Reverts: Reverts a previous commit.
  - revert
