name: Security Scan
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: securego/gosec@master
        with:
          args: ./...
